### PR TITLE
Adding DB_FILTER as a variable to the tf module

### PR DESCRIPTION
**Pull request by abhimanyugupta07**
Adding db_filter so that we can enable privileges-grantor on selected databases.

### CODE REVIEW

**Review by max-jacobs — APPROVED** [review]
👍

**Review by patduin — CHANGES_REQUESTED** [review]
Looks good, line in the changelog please :)

**Comment by abhimanyugupta07** [comment]
> Looks good, line in the changelog please :)

Actually, I thought about that. This has not been released yet. So, should we just consider this as part of the first version itself ?

**Comment by patduin** [comment]
> > Looks good, line in the changelog please :)
> 
> Actually, I thought about that. This has not been released yet. So, should we just consider this as part of the first version itself ?

ah ok fine :)

**Review by patduin — APPROVED** [review]

**Review by massdosage — APPROVED** [review]

**Pull request merged**
